import type { Finding, Explanation, MethodologyData } from "../../../shared/types";
import { COLORS, getCertaintyColor } from "./certainty-utils";
import CertaintyBadge from "./CertaintyBadge";
import EvidenceSection from "./EvidenceSection";
import FeedbackWidget from "./FeedbackWidget";

interface ExplanationPanelProps {
  activeData: Finding | { explanation: Partial<Explanation> } | null;
  isOverview: boolean;
  findingIndex: number;
  total: number;
  onNavigate: (dir: number) => void;
  overallCertainty: number;
  findingsCount: number;
  overviewData: MethodologyData | undefined;
}

export default function ExplanationPanel({ activeData, isOverview, findingIndex, total, onNavigate, overallCertainty, findingsCount, overviewData }: ExplanationPanelProps) {
  if (!activeData) return null;

  const certainty = isOverview ? overallCertainty : (activeData as Finding).certainty;
  const expl = activeData.explanation;
  const id = isOverview ? "overview" : (activeData as Finding).id;

  return (
    <div
      role="complementary"
      aria-label="Explanation panel"
      style={{ display: "flex", flexDirection: "column", height: "100%", fontFamily: "inherit" }}
    >
      <div style={{ padding: "16px 20px 12px", borderBottom: `1px solid ${COLORS.border}`, flexShrink: 0 }}>
        <div
          style={{
            fontSize: 10,
            fontWeight: 700,
            textTransform: "uppercase",
            letterSpacing: 1.2,
            color: COLORS.textMuted,
            marginBottom: 8,
          }}
        >
          Explanation
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
          <button
            aria-label="Previous finding"
            onClick={() => onNavigate(-1)}
            style={{
              border: `1px solid ${COLORS.border}`,
              background: "#fff",
              borderRadius: 4,
              padding: "2px 8px",
              cursor: "pointer",
              fontSize: 14,
              color: COLORS.text,
            }}
          >
            ←
          </button>
          <span style={{ fontSize: 11, color: COLORS.textMuted, fontWeight: 500 }}>
            {isOverview ? "Overview" : `${findingIndex + 1} of ${total}`}
          </span>
          <button
            aria-label="Next finding"
            onClick={() => onNavigate(1)}
            style={{
              border: `1px solid ${COLORS.border}`,
              background: "#fff",
              borderRadius: 4,
              padding: "2px 8px",
              cursor: "pointer",
              fontSize: 14,
              color: COLORS.text,
            }}
          >
            →
          </button>
        </div>
      </div>

      <div style={{ flex: 1, overflow: "auto", padding: "16px 20px" }}>
        <h3 style={{ fontSize: 15, fontWeight: 700, color: COLORS.text, margin: "0 0 10px", lineHeight: 1.3 }}>
          {isOverview
            ? (overviewData?.explanation?.title || "Report Methodology")
            : (expl?.title || "Explanation")}
        </h3>
        <div style={{ marginBottom: 12 }}>
          <span
            style={{
              fontSize: 10,
              fontWeight: 600,
              textTransform: "uppercase",
              letterSpacing: 0.8,
              color: COLORS.textMuted,
              marginRight: 8,
            }}
          >
            Certainty
          </span>
          <CertaintyBadge value={certainty || 50} />
        </div>

        {isOverview && (
          <>
            <p style={{ fontSize: 13, lineHeight: 1.75, color: COLORS.textSecondary, margin: "0 0 4px", whiteSpace: "pre-wrap" }}>
              {overviewData?.explanation?.text || `This report was generated by DoublyAI using a multi-agent pipeline: Research Agent gathered evidence, Synthesis Agent drafted findings, and Verification Agent adversarially reviewed each claim. The overall certainty of ${overallCertainty}% is the arithmetic mean of all ${findingsCount} finding scores. Scores above 90% require 3+ corroborating sources and 0 contradictions. Scores below 25% result in finding removal.`}
            </p>
            <EvidenceSection title="Supporting Evidence" items={overviewData?.explanation?.supportingEvidence} color={COLORS.green} />
            <EvidenceSection title="Contrary Evidence" items={overviewData?.explanation?.contraryEvidence} color={COLORS.red} />
          </>
        )}

        {!isOverview && (
          <>
            <div
              style={{
                background: getCertaintyColor(certainty ?? 50) + "08",
                border: `1px solid ${getCertaintyColor(certainty ?? 50)}20`,
                borderRadius: 4,
                padding: "6px 10px",
                marginBottom: 14,
                fontSize: 12,
                color: COLORS.textSecondary,
                fontStyle: "italic",
                lineHeight: 1.5,
              }}
            >
              Finding: &ldquo;{(activeData as Finding).text}&rdquo;
            </div>
            <p style={{ fontSize: 13, lineHeight: 1.75, color: COLORS.textSecondary, margin: "0 0 4px", whiteSpace: "pre-wrap" }}>
              {expl?.text}
            </p>
            <EvidenceSection title="Supporting Evidence" items={expl?.supportingEvidence} color={COLORS.green} />
            <EvidenceSection title="Contrary Evidence" items={expl?.contraryEvidence} color={COLORS.red} />
          </>
        )}

        <FeedbackWidget findingId={id} key={id} />
      </div>
    </div>
  );
}
